<?php

namespace Proxies\__CG__\uni\Bundle\SeriesBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class series extends \uni\Bundle\SeriesBundle\Entity\series implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'id', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'nombreSerie', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'foto', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'sipnosis', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'fechaComienzo', 'categoria', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'allpremios', 'allnoticias');
        }

        return array('__isInitialized__', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'id', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'nombreSerie', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'foto', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'sipnosis', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'fechaComienzo', 'categoria', '' . "\0" . 'uni\\Bundle\\SeriesBundle\\Entity\\series' . "\0" . 'allpremios', 'allnoticias');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (series $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreSerie($nombreSerie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreSerie', array($nombreSerie));

        return parent::setNombreSerie($nombreSerie);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreSerie', array());

        return parent::getNombreSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', array($foto));

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', array());

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setSipnosis($sipnosis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSipnosis', array($sipnosis));

        return parent::setSipnosis($sipnosis);
    }

    /**
     * {@inheritDoc}
     */
    public function getSipnosis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSipnosis', array());

        return parent::getSipnosis();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaComienzo($fechaComienzo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaComienzo', array($fechaComienzo));

        return parent::setFechaComienzo($fechaComienzo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaComienzo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaComienzo', array());

        return parent::getFechaComienzo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\uni\Bundle\SeriesBundle\Entity\categorias $categoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', array($categoria));

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', array());

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function addAllpremio(\uni\Bundle\SeriesBundle\Entity\premios $allpremios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAllpremio', array($allpremios));

        return parent::addAllpremio($allpremios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAllpremio(\uni\Bundle\SeriesBundle\Entity\premios $allpremios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAllpremio', array($allpremios));

        return parent::removeAllpremio($allpremios);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllpremios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllpremios', array());

        return parent::getAllpremios();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addAllnoticia(\uni\Bundle\SeriesBundle\Entity\noticias $allnoticias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAllnoticia', array($allnoticias));

        return parent::addAllnoticia($allnoticias);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAllnoticia(\uni\Bundle\SeriesBundle\Entity\noticias $allnoticias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAllnoticia', array($allnoticias));

        return parent::removeAllnoticia($allnoticias);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllnoticias()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllnoticias', array());

        return parent::getAllnoticias();
    }

}
