categorias:
    path:     /
    defaults: { _controller: "uniSeriesBundle:categorias:index" }

categorias_show:
    path:     /{id}/show
    defaults: { _controller: "uniSeriesBundle:categorias:show" }

categorias_new:
    path:     /new
    defaults: { _controller: "uniSeriesBundle:categorias:new" }

categorias_create:
    path:     /create
    defaults: { _controller: "uniSeriesBundle:categorias:create" }
    requirements: { _method: post }

categorias_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniSeriesBundle:categorias:edit" }

categorias_update:
    path:     /{id}/update
    defaults: { _controller: "uniSeriesBundle:categorias:update" }
    requirements: { _method: post|put }

categorias_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniSeriesBundle:categorias:delete" }
    requirements: { _method: post|delete }
    
    
