noticias_buscar:
    path:     /buscar
    defaults: { _controller: "uniSeriesBundle:noticias:buscarNoticias" }

noticias_responder:
    path:     /responder
    defaults: { _controller: "uniSeriesBundle:noticias:responderNoticias" }
    requirements: { _method: post|put }
    
uni_series_noticias:
    resource: "@uniSeriesBundle/Resources/config/routing/conseguridad/noticiasSeguridad.yml"
    prefix:   /conseguridad