premios:
    path:     /
    defaults: { _controller: "uniSeriesBundle:premios:index" }

premios_show:
    path:     /{id}/show
    defaults: { _controller: "uniSeriesBundle:premios:show" }

premios_new:
    path:     /new
    defaults: { _controller: "uniSeriesBundle:premios:new" }

premios_create:
    path:     /create
    defaults: { _controller: "uniSeriesBundle:premios:create" }
    requirements: { _method: post }

premios_edit:
    path:     /{id}/edit
    defaults: { _controller: "uniSeriesBundle:premios:edit" }

premios_update:
    path:     /{id}/update
    defaults: { _controller: "uniSeriesBundle:premios:update" }
    requirements: { _method: post|put }

premios_delete:
    path:     /{id}/delete
    defaults: { _controller: "uniSeriesBundle:premios:delete" }
    requirements: { _method: post|delete }
